/**
 * Generates src/openings.data.ts from the committed lichess-org/chess-openings
 * TSVs (public domain). EPDs are computed by replaying each line with chessops
 * — the same code path used at runtime — so lookups match by construction.
 *
 * Run: pnpm --filter @tempo/chess-core build:openings
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { makeFen } from "chessops/fen";
import { parsePgn, startingPosition } from "chessops/pgn";
import { parseSan } from "chessops/san";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "data", "openings");
const outFile = join(here, "..", "src", "openings.data.ts");

interface Row {
  eco: string;
  name: string;
  pgn: string;
  epd: string;
  plyCount: number;
}

const byEpd = new Map<string, Row>();
let skipped = 0;

for (const file of readdirSync(dataDir).filter((f) => f.endsWith(".tsv")).sort()) {
  const lines = readFileSync(join(dataDir, file), "utf8").split("\n");
  for (const line of lines.slice(1)) {
    if (!line.trim()) continue;
    const [eco, name, pgn] = line.split("\t");
    if (!eco || !name || !pgn) continue;

    const game = parsePgn(pgn)[0];
    if (!game) {
      skipped++;
      continue;
    }
    const pos = startingPosition(game.headers).unwrap();
    let plyCount = 0;
    let ok = true;
    for (const node of game.moves.mainline()) {
      const move = parseSan(pos, node.san);
      if (!move) {
        ok = false;
        break;
      }
      pos.play(move);
      plyCount++;
    }
    if (!ok || plyCount === 0) {
      skipped++;
      continue;
    }
    const epd = makeFen(pos.toSetup(), { epd: true });
    // First entry wins on transposition collisions (dataset lists the
    // canonical move order first).
    if (!byEpd.has(epd)) {
      byEpd.set(epd, { eco, name, pgn: pgn.trim(), epd, plyCount });
    }
  }
}

const rows = [...byEpd.values()];
const json = JSON.stringify(rows);
const source = `// GENERATED by scripts/build-openings.ts — do not edit.
// Source: lichess-org/chess-openings (public domain). ${rows.length} openings.

export const OPENINGS_JSON: string = ${JSON.stringify(json)};
`;
writeFileSync(outFile, source, "utf8");
console.log(`Wrote ${rows.length} openings to openings.data.ts (${skipped} rows skipped).`);
